include/mujoco/mjrender.h, include/mujoco/mjvisualize.h
This PR added necessary annotations, following what we did for mjData
and mjModel for length of the given array.
This is useful because my parser used this info to generate Swift interface:
https://github.com/liuliu/swift-mujoco/blob/main/Sources/codegen/main.swift#L297
such that the access to underlying array is bound-checked.
Please let me know if this makes sense. After this change, I can
successfully generate all mj* struct interfaces in Swift without problem
(with notable exception of mjui): https://github.com/liuliu/swift-mujoco/tree/main/Sources
=> Add annotations for length of a given array in mj* structs

unity/Editor/Components/MjGeomEditor.cs, unity/Runtime/Components/Joints/MjHingeJoint.cs, unity/Runtime/Components/Sensors/MjSiteVectorSensor.cs, unity/Runtime/Components/Shapes/MjGeomSettings.cs
This PR makes some small fixes to the Unity plugin to make it work with our controller
If desired, I could split this PR up but that would be a bit of work.
- Fixed offsets for the sensor readings. The sensor offset was multiplied by 3 twice. (MjSiteVectorSensor.cs)
- Added advanced settings to MjGeomEditor to be able to tune contact parameters (MjGeomEditor.cs)
- Added a raw configuration field to the hinge joint with double precision, to allow reading the angle of a continous joint without normalization
- Added the priority field to geometry to allow setting geometry priority for collisions
=> Fixing sensor reading in Unity, expose Advanced Settings property in Editor and add Priority tag to geometry

CMakeLists.txt
With CMAKE_CURRENT_SOURCE_DIR mujoco will be able to compile as subproject with CMake's FetchContent feature.
=> Using CMAKE_CURRENT_SOURCE_DIR to refer to mujoco's include directory

src/engine/engine_print.c, src/render/render_gl2.c
I am running through [simulate.swift](https://github.com/liuliu/swift-mujoco/blob/main/Examples/simulate/main.swift) (my port of simulate.cc) with
address sanitizer to discover related bugs.
Besides ones in my port, there are two in MuJoCo:
1. in maketext, the logic to find . is not protected against j is less
than 0 (due to the decreasing logic above), creating out of bound
access.
2. in mj_printFormattedData, qfrc_applied should use length nv not nq,
otherwise out of bound access could be triggered.
Test Plan:
Run through the simulate.cc with asan. Before this fix, when presenting
profiler view, it will trigger bug #1. When print data, it will trigger
bug #2. Both are using model/humanoid/22_humanoids.xml.
=> Fix two asan detected memory bugs

simulate/simulate.cc
The merge commit of #201 (e40b9da18120c73f5c26fcd3899d8b0ff5f21a2a) changed
```while (this->loadrequest > 0)```
to
```cond_loadrequest.wait(lock, [this]() { return this->loadrequest > 0; });```
but `wait` is equivalent to `while(!pred())` so it needs to be
```cond_loadrequest.wait(lock, [this]() { return this->loadrequest == 0; });```
or there is a race condition. Presumably this did not come up in testing because it only causes a segmentation fault when the caller of `load` function quickly destroys the `m` and `d` objects (which Python does and the pure C++ `simulate` does not).
=> Fix simulate condition variable predicate

doc/APIreference.rst, include/mujoco/mjvisualize.h
Figured this out while using the feature however it wasn't hard to find the `+1` [in the rendering code](https://github.com/deepmind/mujoco/blob/7a0e0ed80cf65aa4f5142b1ee197c1f0c0a44955/src/render/render_gl3.c#L265)
as well.
The rendered color needs to be `segid+1` so that the value "0" can represent "nothing".
=> Fix off by one in segmentation with IDCOLOR documentation

python/setup.py
Since `cp` is unavailable on Windows `setup.py` exits with an error. Using `shutil.copyfile` fixes it.
=> Swap out cp call with shutil.copyfile closes #462

doc/Makefile, sample/Makefile, sample/Makefile.macos, sample/Makefile.windows
- update of old/stale PR https://github.com/deepmind/mujoco/pull/31
- See https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html and https://stackoverflow.com/questions/2145590/what-is-the-purpose-of-phony-in-a-makefile for details
- Also, since [`.PHONY` targets are cumulative](https://lists.gnu.org/archive/html/help-make/2010-02/msg00118.html), it's often cleaner to declare the phony next to the command instead of a giant blob
=> build(makefile): Non-file Makefile targets should have .PHONY

unity/Runtime/Tools/XmlElementExtensions.cs
Update float parsing using InvariantCulture to not depend on OS language to parse float value. Usefull for French, German, ... users where comma is default notations for the decimal point parsing.
=> Better XML float parsing

unity/Runtime/Components/Equality/MjWeld.cs, unity/Runtime/Tools/MjEngineTool.cs
Fix according to advice in #486. In case someone wants to test it, it should be noted that this version of the plugin does not work with the prebuilt 2.2.2 dll, I think due to recent changes to the bindings in 1e2a9a53bcca2e2bf6758b350db32346d132098d (is a new release coming?). I tested the changes with a 2.2.2 friendly version at [this fork](/Balint-H/mujoco).
=> Fix MjWeld using wrong address in Unity plugin

doc/changelog.rst
I tested the version 2.3.0 and found the two ends of a cable object are exposed as B_first & B_last instead of B_left & B_right.
=> Correct end element's exposure name of cable objects.

unity/Runtime/Components/Shapes/MjMeshFilter.cs
MjMeshFilter did not add appropriate UVs to the new mesh, hence all created meshes were rendered with a single solid colour, missing out on textures, normal maps etc. from their materials. Changes were added based on the Unity [documentation example](https://docs.unity3d.com/ScriptReference/Mesh-uv.html) for creating new meshes.
=> Add new uvs to meshes created so textures and materials can be rendered correctly

unity/Runtime/Components/MjScene.cs
Due to originally submitting PR #253 from the main branch of my fork, the PR got bloated and outdated. I'm submitting this feature update on a separate branch now instead for easier merging.
Additions:
- Events to subscribe for in `MjScene` that are called before, after, or inside the MuJoCo update. This allows explicit definition of order of execution purely in script, and allows processing of control values between kinematics and dynamics conveniently. This is helpful for example when training RL environments to ensure observations collected are up to date, and improve stability of some controllers.
- To aid the setup and shutdown processes in scenes sometimes it is necessary to check if the `MjScene` instance exist. However there was currently no public way for doing so without …
=> Unity MjScene synchronisation events

unity/Runtime/Components/MjGlobalSettings.cs
Adding the multiccd flags for the `MjGlobalSettings` class as suggested by #427. Tested for importing and exporting.
=> Add multiccd option in Unity MJCF parser and writer

unity/Runtime/Components/Joints/MjSlideJoint.cs
Fix typo in `OnSyncState` of `MjSlideJoints`, which previously converted length to degrees.
=> Remove unnecessary unit conversion in MjSlideJoint in Unity plugin

unity/Runtime/Components/Shapes/MjMeshFilter.cs
Addresses issue mentioned by #507, except it solves it not by not deleting meshes in Edit mode (which we want to if the geom changed in edit mode), but by referencing a new mesh when the `MjMeshFilter` is first created. When the new `MeshFilter`'s `sharedMesh` is updated, edited or destroyed, the original geom will now be unaffected. This helps with copy-pasting/duplicating parts of the model quickly without needing to update the old geoms.
=> Fix disappearing meshes on Geom duplicates in Unity Editor

simulate/simulate.h
Riscv64 needs -latomic to be added explicitly on link flags.
Since atomic is used directly, better link it explicitly
[67/71] : && /usr/bin/cmake -E rm -f lib/riscv64-linux-gnu/liblibsimulate.a && /usr/bin/ar qc lib/riscv64-linux-gnu/liblibsimulate.a  simulate/CMakeFiles/libsimulate.dir/glfw_dispatch.cc.o simulate/CMakeFiles/libsimulate.dir/simulate.cc.o simulate/CMakeFiles/libsimulate.dir/uitools.cc.o && /usr/bin/ranlib lib/riscv64-linux-gnu/liblibsimulate.a && : [68/71] /usr/bin/c++ -DEIGEN_MPL2_ONLY -DMJSIMULATE_STATIC -I/<<PKGBUILDDIR>>/simulate -I/<<PKGBUILDDIR>>/include -I/usr/include/libqhull_r -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden …
=> Update cmakelist to fix a link failure on riscv64 (Debian/Ubuntu)

unity/Editor/Bindings.meta
Missing file added to Unity Editor folder, so the folder is included if the MuJoCo is included through git URL instead of a local directory. In that case the package is treated immutable by Unity, and does not automatically add a .meta file. Fixes #481.
=> Add .meta file to Bindings folder

unity/Runtime/Components/Joints/MjJointSettings.cs
Partially fixes #654, applies multiplier depending on `MjSceneImportSettings.AnglesInDegrees`.
=> Fix ignored angle units of springref during Unity import

unity/Runtime/Components/MjComponent.cs
Previously `MjComponent`s requested scene rebuilding at `OnDisable()` from `MjScene` even if it was already destroyed during scene transition. This generated a new MjScene during Scene cleanup, which resulted in a non-breaking error message in the Editor (and I assume some undesired side-effects).
=> Don't access MjScene in OnDisable() if it doesn't exist

src/engine/engine_vfs.c, test/engine/engine_vfs_test.cc
In its current form, the `mj_deleteFileVFS` results in infinite loop with more than one file. This should fix the issue.
=> Fix infinite loop in `mj_deleteFileVFS`

unity/Runtime/Components/Bodies/MjBody.cs, unity/Runtime/Components/MjGlobalSettings.cs, unity/Runtime/Importer/MjXmlModifiers.cs, unity/Runtime/Importer/MjcfImporter.cs
Hi everyone, first timer here! 👋
When testing out MuJoCo I noticed that the balloons model didn't load for me with the unity plugin, so here's a patch which makes it work.
Let me know if you have any feedback 🙂 
---
Steps to reproduce the issue, in unity with plugin setup correctly:
1. Try to load the model located at `model/balloons/balloons.xml`
Result: It fails to load
---
The issues, causing it not to work in unity as expected, was:
* Missing support for the `implicit` integrator type - model failed to load before
* Missing support for `gravcomp` - balloons where just falling down
* Default wind in imported scene - not matching the stand alone simulator, nor the documentation
* The importer skipped defaults for tendons - the strings attaching the balloons to the weight wasn't fixed in …
=> Add support for loading balloons.xml in Unity plugin

unity/Runtime/Components/Shapes/MjGeomSettings.cs, unity/Tests/Editor/Components/MjGeomSettingsTests.cs
~~Tying a buoyant object to the world off center (horizontal offset to CoM), results currently in a never ending oscillation, even if the global settings specifies a viscosity and mass + density are specified.~~ [Edit: This was not the case, see discussion]
In the XML Reference, there's a `fluidshape` attribute that can be used to introduce drag, but this feature is not exposed in the Unity Plugin, nor is it implied.
I've exposed the `fluidshape` attribute for a `geom` as `FluidShapeType` in `MjGeomSettings`, as this is where more advanced settings for geometries are placed. I assume you want it to be placed here to simplify the ux for new users, but let me know if you prefer it directly in `MjGeom`.
The name `FluidShapeType` isn't a 1:1 mapping to the XML attribute, but the naming tries …
=> Add support for fluid shapes to Unity plugin

python/mujoco/__init__.py
The loading of the plugins in `python/mujoco/__init__.py` can fail depending on the used build environment. When the described installation process is followed, everything works fine. However, some build environments can "generously" add `__init__.py` files to all sub-directories, which causes the error `OSError: [...]/mujoco/site-packages/mujoco/plugin/__init__.py: invalid ELF header` as the added `plugin/__init__.py` file is passed to `ctypes.CDLL(...)`.
=> Ensure that loaded plugins are a shared library

src/engine/engine_io.c, test/engine/engine_io_test.cc
Before these changes, the included `EngineIoTest.VerifySizeModel` test fails with the following:
```
mujoco/test/engine/engine_io_test.cc:79: Failure
Expected equality of these values:
file_size
Which is: 2416
mj_sizeModel(model)
Which is: 6488
```
With the fix, the test passes.
=> Fix `mj_sizeModel`

src/user/CMakeLists.txt, src/user/user_mesh.cc
As far as I understand, `TINYOBJLOADER_IMPLEMENTATION` macro is used to be defined in libraries or executables that consume `tinyobjloader` only including its header, without linking the corresponding library. However mujoco (at least with the CMake build system provided in this repo) is already linking the tinyobjloader library in which all the symbols are defined, so there is no need to re-defined them.
=> Remove useless TINYOBJLOADER_IMPLEMENTATION definition when building MuJoCo with CMake

doc/modeling.rst
At the latest docs of modeling section, the effective time constant function for muscle just has one parameter, ``ctrl-act``. But ``act``    is used in this function. So, I think it should be $\tau(\text{ctrl}, \text{act})$ instead of $\tau(\text{ctrl} - \text{act})$.
=> Fix the effective time constant function for muscle

cmake/MujocoDependencies.cmake
While working on another PR, I noticed that the comment block that started with "Override the BUILD_SHARED_LIBS setting" was actually far from the actual code that override the BUILD_SHARED_LIBS setting.
=> MujocoDependencies: Move comment back close to related code

unity/Editor/Exporter/MjExporterEditorWindow.cs, unity/Editor/Exporter/MjExporterEditorWindow.cs.meta
I see using the Unity plugin as a scene construction tool as one of its primary potential use cases. However the existing method for transferring scenes out from Unity is not very user friendly.
This Editor object avoids having to use the debug file from MjGlobalSettings and launching a play mode, and allows saving in a specific location. 
It creates and destroys a MjScene for this purpose to use MjScene's already implemented MJCF construction.
The generated MJCF is not exactly pretty. Having a method to automatically extract defaults or not explicitly write unchanged fields could be further improvements.
=> Add MJCF exporter from Unity based on the importer class

python/mujoco/simulate.cc, python/mujoco/viewer.py, simulate/main.cc, simulate/simulate.cc, simulate/simulate.h
Model loading was moved to the physics thread sometime back (for good reason). This broke the "loading" message shown in UI because the UI did not a know a model was being loaded until after the fact.
The proposed solution adds optional methods to the Simulate class that set and clear a loading message as part of the UI's model loading state machine.
This works with C++ simulate application and the Python managed viewer. It should not affect the passive viewer.
EDIT: It also moves the loading message for command line based reloads to the left of the screen. Previously it was on the right for command line filenames and the left for UI based reloads (button or drag-n-drop) which is inconsistent.
=> simulate: fix display of loading message

unity/Runtime/Components/MjGlobalSettings.cs
Fixes issue where the XML parser extensions were not used in the MjGlobalSettings class's memory options. This previously made it necessary to manually input the default -1 value when importing scenes that have not defined it.
=> Unity Plugin - Use default value of memory option if not present in imported XML

python/mujoco/CMakeLists.txt
Conditionally uses system-wide pybind11 version when `MUJOCO_PYTHON_USE_SYSTEM_PYBIND11` is set.
=> cmake: support system-wide pybind11

unity/Runtime/Components/Joints/MjBallJoint.cs
Tiny fix for a typo, ranges are defined in degrees (no way to change units by the plugin at the moment).
=> Unity Plugin - Fix wrong units indicated in ball joint tooltip

unity/Editor/Components/MjShapeComponentEditor.cs, unity/Runtime/Components/Shapes/MjHeightFieldShape.cs, unity/Runtime/Components/Shapes/MjHeightFieldShape.cs.meta, unity/Runtime/Components/Shapes/MjShapeComponent.cs, unity/Runtime/Tools/MjcfGenerationContext.cs
This PR adds preliminary support for heightfields in the Unity plugin. The hfield type is now allowed to be selected in MjGeom, and lets you reference a Unity terrain object. Heightmaps can be loaded and configured with the built-in Unity tools in the paired terrain component. When the scene MJCF is constructed, the current heightmap of the terrain will be saved as a PNG at a path local to the Application as specified by the user, which will be referenced in the scene's assets.
The current implementation does not support importing heightfields referenced from an MJCF, nor does it support runtime terrain editing, but both are straightforward future additions. 
Let me know if you think it would be better to wait until those features are implemented. …
=> [Unity plugin] Basic support for heightfields

README.md
@nic-barbara and I have just announced the release of our package [MuJoCo.jl](https://github.com/JamieMair/MuJoCo.jl) which has revived the previous version of the Julia bindings for MuJoCo from the [Lyceum group](https://github.com/Lyceum/MuJoCo.jl).
Could we please be listed as the (unofficial) Julia bindings for MuJoCo in `mujoco`'s `README.md`? Our package is supported and up to date with version `2.3.7` of MuJoCo. We're working on updating to version `3.0.0` in the near future.
Thanks!
=> Edited README to update the entry for the Julia 3rd party bindings

unity/Editor/Components/MjMouseSpring.cs, unity/Editor/Components/MjShapeComponentEditor.cs
A small QoL edit, to allow clicking on a geom in scene view, and apply the mouse perturbations without needing to select the parent body in the hierarchy. It also removes the `#if UNITY_EDITOR`  directive, since the Editor only platform was defined in the file's assembly already (#303, 0180d83).
=> Unity Plugin - Enable mouse spring perturbations when clicking on a geom in scene view

unity/Runtime/Components/Joints/MjJointSettings.cs, unity/Runtime/Components/MjActuator.cs
This PR checks for the `autolimit` state of the compiler element of the XML. Without this, the `limited` flag was most often ignored during imports, even when explicitly defined in the XML. This resolves #512, and was the root cause of #1052 and #654.
=> [Unity plugin] Consider "autolimits" in "limited" attributes

unity/Editor/Importer/StlMeshParser.cs
This PR makes modifications to the STL IO of the Unity plugin. Changes:
- Writes only the new bytes of the buffer to the file, which avoids having trailing nulls in the imported and scaled STL. Blender and other STL viewing software treated the files with trailing nulls as corrupted.
- Using a dictionary, indices of shared vertices are reused during the import. This allows loading larger meshes with the same index resolution, and the resulting files are smaller and render faster (~20%-40% smaller asset files in the MPL hand for example).
- Switch to 32bit indexing if 16 bits are not sufficient even with index reusing.
Tested with the MuJoCo mug, and the MPL hand.
It was unclear to me why was it necessary to perform axis swizzling in the STL writer part as well, and not just the parser. As …
=> [Unity plugin] Reuse vertex indices when importing STL meshes

unity/Runtime/Components/MjScene.cs
Addresses #1365. Only expose the callbacks as events, instead of the complete EventHandler. Provide `Model` and `Data` for the callbacks to simplify data access for subscribers.
=> [Unity plugin] Use consistent event interfaces in MjScene 

doc/XMLreference.rst
eq_active is a member of mjData, not mjModel
=> [docs] Fix equality/weld body2 description in XML reference

mjx/mujoco/mjx/_src/smooth.py
Rather updating elements in the solution one-by-one, this patch updates the elements in the same tree depth in parallel. This makes solve_m roughly 2x faster on larger models (10 humanoids benchmark with 270x270 matrix with 2430 sparse elements).
=> Update independent elements in solve_m in parallel

doc/programming/extension.rst
A function `data_open_callback` was defined, but then `str_open_callback` was used.
=> Fix mjpResourceProvider example

unity/Editor/Importer/MjImporterWithAssets.cs, unity/Runtime/Importer/MjcfImporter.cs, unity/Runtime/Plugins.meta, unity/Runtime/Tools/MjEngineTool.cs
This PR is the start of the addition of MuJoCo plugin support (e.g. elasticity) to the Unity plugin. The current additions expect the user to supply the relevant Mj plugin libraries to a "Plugin" folder inside the Unity Package - This is a non ideal situation as it may pose an issue on builds or non-local installs of the Unity Package.
The current state of the PR loads plugins on XML import, letting the built-in parser properly process the file. The Unity scene will then be built based on the processed XML generated by `mj_saveLastXML` as usual. However, the Unity scene will have no idea it was generated from a plugin-using XML, so any effect the plugin would have had post-scene compile is currently lost.
Most of the plugin use cases that are not expected to be completely covered by the …
=> [Unity plugin] Preliminary support for Mj plugins

unity/Runtime/Components/Tendons/MjSpatialTendon.cs
All tendons used to perform the rendering of all tendons (repeating work), and did not render wrapping sections. Also the existing routing connected elements that were not supposed to be.
This PR simply reuses the code from `src/engine/engine_vis_visualize.c`, and adds support for width rendering.
=> [Unity-plugin] Tendon rendering fix

doc/programming/samples.rst, sample/record.cc
Renames the non-existent "render" command to "record"
=> Fix docs for the record command

unity/Runtime/Components/Joints/MjJointSettings.cs, unity/Runtime/Components/MjActuator.cs, unity/Runtime/Tools/XmlElementExtensions.cs
A change between 3.1.2 and 3.1.3 meant that now auto values were written to the intermediary XML the Unity plugin uses for imports, (instead of only explicit `true` or `false` values). This PR handles the auto values now, and sets limited accordingly.
The autolimit field is still eventually lost on XML import, and converted to explicit limited fields. It could be time to add autolimits to MjGlobalOptions class, and switch the Limited field to either "Disable Limit" or an Enum in the Unity plugin.
=> [Unity-plugin] Parse the "auto" value now used in "limited" fields by the XML writer

python/mujoco/viewer.py
This has been annoying me lately, turns out it is a one line fix. Fixes #1116.
[`main.cc`](https://github.com/google-deepmind/mujoco/blob/67982c4961b47a899ee93e988989c0bf2687b72f/simulate/main.cc#L236) always overwrites the `simulate.load_error` on a successful load, which implicitly sets an empty string if the load is successful. The python viewer's `viewer.py` just needs to do the same.
=> [Python Viewer] clear load error on successful reload, fixes #1116

doc/mjx.rst
I tried to run a minimal example explained in mjx docs, but an error occurred as shown below:
therefore, I have changed the ```mjx.device_put(model)``` to ```mjx.put_model(model)```, and the example code works fine. 
I have PR the modified mjx.rst, if my modification needs to be corrected, please tell me how can I fix it in different way.
=> fixed minimal example shown at mjx.rst

unity/Editor/Components/MjActuatorEditor.cs, unity/Runtime/Components/MjActuator.cs, unity/Tests/Editor/Components/MjActuatorTests.cs
Added support for `kv` in position actuators in Unity, missing since 3.1.0 . At first I just reused the `Kv` property of the velocity actuators however that had some undesired quirks, such as the default value being 1 instead of 0 for position actuators, or that changing the parameter value when editing the actuator as a velocity actuator influenced the position actuator. For this reason, I seemingly redundantly declared the `Kvp` parameter, let me know if you have any issues or suggestions for this issue. 
I'm also interested on any potential suggestions for the `intvelocity` actuators which are also missing at the moment, but have their own `kp` and `kv`. I'm considering not tracking all these parameters in MjActuator and its Editor at all in the first place, and have sibling classes …
=> [Unity Plugin] Track separate kv property for position actuators

unity/Runtime/Components/MjGlobalSettings.cs, unity/Runtime/Components/Sensors/MjBaseSensor.cs, unity/Tests/Editor/Components/MjGlobalSettingsTests.cs, unity/Tests/Editor/Components/Sensors/MjBaseSensorTests.cs, unity/Tests/Editor/Importer/MjcfImporterTests.cs
Remove references in MjGlobalOptions and sensor base class to the deprecated sensornoise attribute.
=> [Unity plugin] Remove sensor noise properties

src/user/user_model.cc, test/user/testdata/cube_with_mesh_def.xml
=> Copy all keys of def_map when copying a mjCModel. Fixes #1798

unity/Runtime/Components/Joints/MjHingeJoint.cs, unity/Runtime/Components/Joints/MjSlideJoint.cs
This bug was originally discovered by @joanllobera, thanks!
Previously provided joint axes provided by the C# components were only correct for multi hinge/slide bodies at q0, as the local rotation of the joints in Unity is not kept in sync. This is relevant for joints after the first, whose axes will not travel rigidly in their parent bodies' frame. 
Instead of syncing the local rotations of the joint transforms, I instead return the values stored in data->xaxis when the RotationAxis/SlideAxis properties are queried, as that will be more up to date and involves less operations.
=> [Unity-plugin] Use MuJoCo calculated cartesian axes for hinge and slide

src/user/user_mesh.cc
- In [this commit in v3.17](https://github.com/google-deepmind/mujoco/commit/8e2f830fd2d079d4391541bcbb4971d12e164e88), this was changed from `mju_norm3` to `mjuu_normvec`, but the latter will mutate its input to be normalized instead of just returning the norm.
- Perhaps `mju_norm3` was mistaken as `mju_normalize3` which does mutate its input.
- It looks like this was the only mistakenly changed callsite; other calls to `mju_norm3` were changed to `sqrt(mjuu_dot3(x, x))`
- This causes mesh ray casting to be incorrect; on some meshes I see a large increase in node visits within `mju_rayTree` (this fixes [issue #1875](https://github.com/google-deepmind/mujoco/issues/1875))
- Before commit 8e2f830 on my mesh: `nstack` in `mju_rayTree` ~= 500. After the bug, nstack ~= 30000. With this fix, …
=> Fixed incorrect mesh face circumradius calculation

python/mujoco/__init__.py
This fixes #2119. I've tested that this works by building and installing the python wheels locally with the https://github.com/hartikainen/mjx-bazel-test project.
=> Fix python namespacing

.gitignore
This might be helpful for others who build and test MuJoCo on macos.
=> Add `MUJOCO_LOG.TXT` and `.cache` to `.gitignore`

src/engine/engine_plugin.cc
Previously the return value of dlopen was ignored, meaning a failed load of a shared library would stay unnoticed
Can be tested by compiling this piece of code into a shared library and then trying to load it
```cpp
#include <iostream>
#include <mujoco/mujoco.h>
void test();
mjPLUGIN_LIB_INIT
{
test();
std::cout << "Registering Test Plugin" << std::endl;
}
```
=> Print error instead of failing silently when loading plugins

.github/workflows/build.yml, python/mujoco/specs_test.py, python/mujoco/testdata/model.xml
This PR should fix running `pytest --pyargs mujoco` in an environment in which `mujoco` is installed not in editable mode, by moving the `model.xml` file used by `spec_test.py` to the `testdata` folder of python bindings (as suggested by @saran-t and @yuvaltassa).
Furthermore, I modified the github actions test to ensure that they do not run in the `python/dist` folder, to ensure that they can catch this kind of regressions in the future.
I also integrated @hartikainen suggestions on the use of `epath`.
=> Fix running tests out of a installed mujoco python package

mjx/training_apg.ipynb
Hi! I've put up a paper on arxiv based on this work, it would be great if we could add the citation to the tutorial! I also changed the coloring library for the mathjax equations since \textcolor didn't seem to work on the colab.
I'm not sure how to update the linked colab - does that happen automatically?
=> add citation and fix math symbol text color

doc/changelog.rst, python/mujoco/rollout.cc, python/mujoco/rollout.py, python/mujoco/rollout_test.py
`nroll` can always be implied from the other arguments of rollout.
I grepped the codebase and did not find any cases where `nroll` was being passed to rollout other than its threading test.
=> Remove nroll argument from rollout

doc/changelog.rst, doc/python.rst, python/mujoco/rollout.cc, python/mujoco/rollout.py, python/mujoco/rollout_test.py
`rollout` can now accept a list of models of length `nroll`, similar to its other arguments.
The models must be compatible, meaning `nstate`, `ncontrol`, `nv`, and `nsensordata` must be equal.
=> Allow rollout to accept a list of models of length nroll

.github/workflows/build.yml
The `macos-12` is now deprecated and subject to brownout periods and will be removed soon, see https://github.com/actions/runner-images/issues/10721 . To continue testing macOS with Intel processor, we can switch to use `macos-13`.
=> GitHub Actions: Use macos-13 image instead of deprecated macos-12

test/CMakeLists.txt, test/benchmark/CMakeLists.txt, test/engine/CMakeLists.txt, test/plugin/actuator/CMakeLists.txt, test/plugin/elasticity/CMakeLists.txt, test/plugin/sensor/CMakeLists.txt, test/thread/CMakeLists.txt, test/user/CMakeLists.txt, test/xml/CMakeLists.txt
Before this PR, all instances of `mujoco_test` in the codebase were followed by a call to `target_link_libraries(<testname> fixture gmock)`.
As anyhow `mujoco_test` already was calling target_link_libraries to some predefined list of targets (`mujoco` and `gtest_main`), this PR adds to the list of default linked targets also `fixture` and `gmock`, to reduce the boilerplate required to add a test.
Furthermore, to completely remove the need for calling target_link_libraries after a call to `mujoco_test`, this PR also adds to the `mujoco_test` macro the `ADDITIONAL_LINK_LIBRARIES` argument, that can be used if a given test needs to link some additional targets beside the default ones.
To permit to use these new features also for mujoco benchmarks, this PR adds a `MAIN_TARGET` parameter to …
=> Reduce cmake test boilerplate

doc/unity.rst
Add a link to the mj-unity tutorial, and update the information provided to reflect the features added over time.
=> [Unity plugin] Reference the tutorial in the Unity plugin docs

python/mujoco/rollout.cc, python/mujoco/rollout.py, python/mujoco/rollout_test.py
Thanks to @milutter for reporting these bugs.
=> rollout: fix bugs in checking list lengths, add tests

src/user/user_mesh.cc, src/user/user_objects.h
Generalize num_face_vertices_ type in mjCMesh object to be the type of tiny_obj_loader.
Fix #2332 
@yuvaltassa FYI
=> Generalize num_face_vertices_ type in mjCMesh object to be the type of tiny_obj_loader. Fixes #2332

python/mujoco/codegen/generate_spec_bindings.py, python/mujoco/specs.cc, python/mujoco/specs_test.py
Fixes issue mentioned here in https://github.com/google-deepmind/mujoco/discussions/2289.
=> Fix MjSpec introspection with `visual.rgba`, `visual.headlight`, and `visual.global_`.

python/mujoco/rollout.cc, python/mujoco/rollout_test.py
`rollout.cc` used `int` types for pointer arithmetic and checking the array size. This limited the state/sensordata arrays to about 2^31 - 1 elements due to an `int` limited size check in `rollout.cc`. The fix is to use `size_t` in the appropriate places.
I wrote a test that initially failed and now passes. But if the test passes, it means a very long rollout was run. With 24 threads the test took just over 3 minutes. So I did not add the test to `rollout_test.py`. The test function is:
```python
def test_large_state(self):
model = mujoco.MjModel.from_xml_string(TEST_XML)
nstate = mujoco.mj_stateSize(model, mujoco.mjtState.mjSTATE_FULLPHYSICS)
data = mujoco.MjData(model)
nthread = 24
nbatch = nthread
nstep = ((2**31) // (nstate*nbatch)) + 2
assert nstep * nstate * nbatch > 2**31 …
```
=> rollout use size_t for array size check and pointer arithmetic

python/mujoco/simulate.cc, python/mujoco/viewer.py, simulate/simulate.cc, simulate/simulate.h
See issue #2494 
Added the text and image overlay handles in the style of commit [37d759](https://github.com/google-deepmind/mujoco/commit/37d7591ce0d1424f6853dd9293eec1579c8e623f).
This supports:
[Brax PR 584](https://github.com/google/brax/pull/584)
[Playground PR 83](https://github.com/google-deepmind/mujoco_playground/pull/83)
=> Add handles for overlaying user text and images to the Passive Viewer

unity/Editor/Importer/MjImporterWithAssets.cs, unity/Editor/Importer/ObjMeshImportUtility.cs, unity/Editor/Importer/ObjMeshImportUtility.cs.meta, unity/Runtime/Components/Shapes/MjMeshFilter.cs, unity/Runtime/Components/Shapes/MjMeshShape.cs
This feature handles OBJ mesh assets referenced in MJCF. It applies the scale to the OBJ mesh then saves it as a local asset in the project, after swizzling the mesh coordinates. An additional step is taken to enable read-write of mesh data from obj files. We flip around mesh faces if the scale has an odd number of negative numbers. In fact this is a missing detail from the STL parser, will add a fix for that soon in a separate PR.
A related feature included is by default now the mesh renderer is turned of Geoms with group >=3 (default function with Simulate). This will make imported scenes appear more similar to what is expected from the Simulate UI (commonly collision geoms are hidden by default using this approach).
This now enables importing many more menagerie models to Unity. …
=> [Unity plugin] Add support for OBJ file import from MuJoCo scenes

cmake/MujocoDependencies.cmake
Removed PATCH_COMMAND for cmake_minimum_required updates and added checks for CMAKE_POLICY_VERSION_MINIMUM.
=> [cmake branch] Refactor cmake_minimum_required handling in dependencies
